name: Testes com Jest

on: pull_request

jobs:
  testes-com-jest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with: 
          node-version: 20.x
      - name: Rodando testes unit√°rios
        run: |
          npm install
          npm test
